import "./globals.css";
import Header from '../components/Header.jsx'



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="bg-black"
      >
        <div className="text-3xl text-yellow-500  py-3 ">
          <Header />
         </div>
        <span className='text-2xl mt-5 p-3'>
          {children}
        </span>

      </body>
    </html>
  );
}
